# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e27ab99d6e634ca1e6956d48829024d0765f17d60a9b950fd9cda02b04dbae215c5a2a1794ea023e30d13c9e470dfcbdf5920f8b17dce0db65032d26bc572254

test:
  secret_key_base: 382c47e2b088f7d7f9d9d08ac2626f9d3763739dedd802e2385bf1cf54ed1e978028c2fe8d8ea0da3b6a1c9b1e4cf38846ed9db4050dc025417948396a29f092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
